export const certificateModalContent = {
  title: 'Купить сертификат',
  subtitle: 'Оформите подарочный сертификат на прыжок с парашютом',
  denominations: [
    { value: '17400', label: 'Тандем прыжок — 17 400 ₽' },
    { value: '7900', label: 'Самостоятельный прыжок — 7 900 ₽' },
    { value: '130000', label: 'Курс обучения — 130 000 ₽' },
    { value: 'custom', label: 'Своя сумма' },
  ],
  fields: {
    recipientName: 'Имя получателя',
    recipientNamePlaceholder: 'Иван',
    recipientLastName: 'Фамилия получателя',
    recipientLastNamePlaceholder: 'Петров',
    recipientPhone: 'Телефон получателя',
    recipientPhonePlaceholder: '+7 (999) 123-45-67',
    denomination: 'Номинал сертификата',
    customAmount: 'Своя сумма',
    senderName: 'Ваше имя (необязательно)',
    senderNamePlaceholder: 'Александр',
    message: 'Пожелание (необязательно)',
    messagePlaceholder: 'С наилучшими пожеланиями...',
  },
  submit: 'Оформить сертификат',
  submitting: 'Оформляем...',
  privacy: 'Нажимая кнопку, вы соглашаетесь с обработкой персональных данных',
  success: {
    title: 'Сертификат оформлен!',
    message: 'Мы отправим сертификат на указанный email в течение часа',
  },
}
