export const galleryContent = {
  badge: 'Галерея',
  title: 'ФОТО И ВИДЕО',
  titleAccent: 'С КЛУБА ЕССАВИЯ',
  description:
    'Взгляните на наши прыжки, полеты и события через объектив камеры. Здесь собраны лучшие моменты из жизни нашего аэроклуба.',
  categories: [
    { value: 'all', label: 'Все' },
    { value: 'tandem', label: 'Тандем' },
    { value: 'solo', label: 'Соло' },
    { value: 'sport', label: 'Спорт' },
    { value: 'training', label: 'Обучение' },
  ],
  media: [
    {
      id: 1,
      type: 'image',
      src: '/images/gallery/skydiver-1.jpg',
      title: 'Свободное падение',
      description: 'Момент свободного падения на высоте 3000 метров.',
      category: 'sport',
      date: '15.03.2024',
      participants: '1',
    },
    {
      id: 2,
      type: 'image',
      src: '/images/gallery/skydiver-2.jpg',
      title: 'Групповой прыжок',
      description: 'Командная работа в свободном падении.',
      category: 'sport',
      date: '20.03.2024',
      participants: '4',
    },
    {
      id: 3,
      type: 'image',
      src: '/images/gallery/skydiver-3.jpg',
      title: 'Захват флага',
      description: 'Спортивный прыжок с захватом флага.',
      category: 'sport',
      date: '25.03.2024',
      participants: '2',
    },
    {
      id: 4,
      type: 'image',
      src: '/images/gallery/skydiver-4.jpg',
      title: 'Тренировочный прыжок',
      description: 'Отработка учебных элементов.',
      category: 'training',
      date: '28.03.2024',
      participants: '1',
    },
    {
      id: 5,
      type: 'image',
      src: '/images/gallery/skydiver-5.jpg',
      title: 'Посадка на точность',
      description: 'Приземление в заданную точку.',
      category: 'sport',
      date: '01.04.2024',
      participants: '1',
    },
    {
      id: 6,
      type: 'image',
      src: '/images/gallery/skydiver-6.jpg',
      title: 'Прыжок с Ан-2',
      description: 'Прыжок с учебного самолета Ан-2.',
      category: 'training',
      date: '05.04.2024',
      participants: '3',
    },
    {
      id: 7,
      type: 'image',
      src: '/images/gallery/skydiver-7.jpg',
      title: 'Ночной прыжок',
      description: 'Спортивный прыжок в вечернее время.',
      category: 'sport',
      date: '10.04.2024',
      participants: '2',
    },
    {
      id: 8,
      type: 'image',
      src: '/images/gallery/skydiver-8.jpg',
      title: 'Соло-прыжок',
      description: 'Самостоятельный прыжок курсанта.',
      category: 'solo',
      date: '12.04.2024',
      participants: '1',
    },
    {
      id: 9,
      type: 'image',
      src: '/images/gallery/skydiver-9.jpg',
      title: 'Тандем-прыжок',
      description: 'Совместный прыжок с инструктором.',
      category: 'tandem',
      date: '15.04.2024',
      participants: '2',
    },
    {
      id: 10,
      type: 'image',
      src: '/images/gallery/skydiver-10.jpg',
      title: 'Групповая акробатика',
      description: 'Выполнение групповых фигур в свободном падении.',
      category: 'sport',
      date: '18.04.2024',
      participants: '6',
    },
  ],
}
