export const galleryContent = {
  badge: 'Галерея',
  title: 'ФОТО И ВИДЕО',
  titleAccent: 'С КЛУБА ЕССАВИЯ',
  description:
    'Взгляните на наши прыжки, полеты и события через объектив камеры. Здесь собраны лучшие моменты из жизни нашего аэроклуба.',
  categories: [
    { value: 'all', label: 'Все' },
    { value: 'tandem', label: 'Тандем' },
    { value: 'solo', label: 'Соло' },
    { value: 'sport', label: 'Спорт' },
    { value: 'training', label: 'Обучение' }
  ],
  media: [
    {
      id: 1,
      type: 'image',
      src: '/images/gallery/tandem-1.svg',
      title: 'Тандем-прыжок на закате',
      description:
        'Незабываемый момент свободного падения с инструктором на фоне заката над Ессентуками.',
      category: 'tandem',
      date: '15.03.2024',
      participants: '2',
    },
    {
      id: 2,
      type: 'image',
      src: '/images/gallery/solo-1.svg',
      title: 'Идеальная посадка соло-прыжка',
      description: 'Точное приземление после самостоятельного прыжка с парашютом Д-1-5у.',
      category: 'solo',
      date: '22.03.2024',
      participants: '1',
    },
    {
      id: 3,
      type: 'image',
      src: '/images/gallery/sport-1.svg',
      title: 'Групповой спортивный прыжок',
      description: 'Команда из 8 человек выполняет сложную фигуру в свободном падении.',
      category: 'sport',
      date: '10.04.2024',
      participants: '8',
    },
    {
      id: 4,
      type: 'image',
      src: '/images/gallery/training-1.svg',
      title: 'Теоретическое занятие по подготовке',
      description:
        'Курсанты изучают конструкцию парашюта и правила безопасности перед практическими прыжками.',
      category: 'training',
      date: '05.04.2024',
      participants: '6',
    },
    {
      id: 5,
      type: 'image',
      src: '/images/gallery/sport-1.svg',
      title: 'Прыжок с вертолета МИ-8',
      description: 'Спортивный прыжок с вертолета Ми-8 на высоту 2500 метров.',
      category: 'sport',
      date: '01.04.2024',
      participants: '4',
    },
    {
      id: 6,
      type: 'image',
      src: '/images/gallery/aircraft-1.svg',
      title: 'Самолет Ан-2 на взлетно-посадочной полосе',
      description: 'Надежный рабочий конь для ознакомительных полетов и прыжков.',
      category: 'aircraft',
      date: '28.03.2024',
      participants: '0',
    },
    {
      id: 7,
      type: 'image',
      src: '/images/gallery/aircraft-1.svg',
      title: 'Самолет Вильга 35-а для полетов',
      description:
        'Легкий спортивный самолет для полетов по программе подготовки пилотов-любителей.',
      category: 'aircraft',
      date: '20.03.2024',
      participants: '0',
    },
    {
      id: 8,
      type: 'image',
      src: '/images/gallery/equipment-1.svg',
      title: 'Парашют типа "Крыло" в сборе',
      description: 'Современный парашют для выполнения сложных фигур в свободном падении.',
      category: 'equipment',
      date: '12.03.2024',
      participants: '0',
    },
    {
      id: 9,
      type: 'video',
      src: '/images/gallery/tandem-1.svg',
      title: 'Видео: Тандем-прыжок с высоты 4000м',
      description: 'Полный видеоролик тандем-прыжка: от инструктажа до мягкой посадки.',
      category: 'tandem',
      date: '10.03.2024',
      participants: '2',
    },
    {
      id: 10,
      type: 'video',
      src: '/images/gallery/solo-1.svg',
      title: 'Видео: Групповая фигура в свободном падении',
      description: 'Команда из 6 человек выполняет сложную построечную фигуру.',
      category: 'sport',
      date: '05.04.2024',
      participants: '6',
    },
  ],
}
